name: CI/CD - Backend Repo

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you're using

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: FLASK_ENV=testing pytest